pipeline
{
agent any
tools {
  maven 'maven_home'
}

stages{

    stage('build')
    {
        steps {
            sh 'mvn -B -DskipTests clean package'
        }


            }

    }

   

    
}

}